### ISSUE TITLE
Actualizacion_AccesoAInfo_Documentar

### ISSUE THREAD

**Issue by MrsPotatoeHead** [MrsPotatoeHead/segundaPreEntrega-Benjamin#2]
Hola, buenas tardes Profe. 
Te comento, estoy teniendo problemas en la actualización tanto del stock cuando se cierra finaliza la compra, envia el mail y en la consola puedo ver que recibo la información con el descuento pero no me pushea, ese nuevo dato a la DB. Lo mismo me pasa cuando actualizo la informacion de algún producto, me entra dentro del codigo como que se actualizó la información pero no me la pushea a la DB.
Después en el tema documentación no supe como documetar el tema de seguridad, en el archivo que compartiste esta documentado el tema con el JWT, yo estuve leyendo para poder hacerlo con cookie y no pude desifrarlo el tema de como escribir el bearer.
Después en el integrador anterir, pedía  esta ruta  /api/users/premium/:uid , yo la cambie por /api/users/premium/:email, porque no me accedia a la información si lo hacia por id, pero cuando queria leer la info del user si me permitia ir por id. German me pidio cambiar a la ruta por :uid, pero no se como resolver el tema de la info.
Muchas gracias.

**Comment by alexmarinmendez** [comment]
Crea una ISSUE por cada problema que tengas en el código. No una sola que explica todos. Sino una por cada uno.

**Comment by alexmarinmendez** [comment]
Reportas problemas con la BD pero en el código no veo que uses persistencia en BD, estás usando persistencia en archivo.

**Comment by alexmarinmendez** [comment]
He probado la actualización de producto PUT /api/products/:pid y si está actualizando correctamente (persistencia en archivo)

**Comment by alexmarinmendez** [comment]
La parte de documentación y el usuario premium no las encuentro en el código

**Comment by MrsPotatoeHead** [comment]
ahi lo separe!, no habia entendido tan rápido después de todo!, gracias profe
